<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE log [
 <!ELEMENT log (Visit*,Page*,Visitor*)>
 <!ELEMENT Page (url)>
 <!ATTLIST Page pid CDATA #REQUIRED>
 <!ELEMENT url (#PCDATA)>
 <!ELEMENT Visit (vdate, vtime)>
 <!ATTLIST Visit tid CDATA #REQUIRED>
 <!ELEMENT vdate (#PCDATA)>
 <!ELEMENT vtime (#PCDATA)>
 <!ATTLIST Visit PageREF CDATA #REQUIRED>
 <!ATTLIST Visit VisitorREF CDATA #REQUIRED>
 <!ELEMENT Visitor (ip)>
 <!ATTLIST Visitor vid CDATA #REQUIRED>
 <!ELEMENT ip (#PCDATA)>
]>

<log>
  <Visit tid="1" PageREF="100" VisitorREF="101">
    <vdate>"2021-09-30"</vdate>
    <vtime>"20:03:44"</vtime>
  </Visit>
  <Visit tid="2" PageREF="200" VisitorREF="102">
    <vdate>"2021-08-31"</vdate>
    <vtime>"08:03:34"</vtime>
  </Visit>
  <Visit tid="3" PageREF="300" VisitorREF="101">
    <vdate>"2022-03-31"</vdate>
    <vtime>"08:05:34"</vtime>
  </Visit>
  <Visit tid="4" PageREF="200" VisitorREF="104">
    <vdate>"2022-01-31"</vdate>
    <vtime>"08:03:00"</vtime>
  </Visit>
  <Visit tid="5" PageREF="200" VisitorREF="105">
    <vdate>"2021-12-31"</vdate>
    <vtime>"08:01:34"</vtime>
  </Visit>
  
  <Page pid="100">
    <url>"http://artificium.us/lessons/l101.html"</url>
  </Page>
  <Page pid="200">
    <url>"http://articificum.us/courses/cs1100.html"</url>
  </Page>
  <Page pid="300">
    <url>"http://articificum.us/courses/cs1000.html"</url>
  </Page>
  <Page pid="400">
    <url>"http://articificum.us/courses/cs2100.html"</url>
  </Page>
  <Page pid="500">
    <url>"http://articificum.us/courses/cs5200.html"</url>
  </Page>
  <Page pid="600">
    <url>"http://articificum.us/courses/cs6600.html"</url>
  </Page>

  <Visitor vid="101">
         <ip>165.11.33.45</ip>
  </Visitor>
  <Visitor vid="102">
         <ip>165.11.33.41</ip>
  </Visitor>
  <Visitor vid="103">
         <ip>165.11.33.42</ip>
  </Visitor>
  <Visitor vid="104">
         <ip>165.11.33.43</ip>
  </Visitor>
  <Visitor vid="105">
         <ip>165.11.33.46</ip>
  </Visitor>
  
</log>